services:
  breast_cancer_predictor:
    image: ttimbers/breast_cancer_predictor_py:68a7b37
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
      