name: breast_cancer_predictor
#name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - ipykernel
  - pandas
  - python
  - scikit-learn
  - vegafusion
  - vegafusion-jupyter
  - vegafusion-python-embed
  - vl-convert-python
  - requests
  - notebook
  - nb_conda_kernels
#  - jupyter_contrib_nbextensions
#prefix: /Users/timberst/miniconda3/envs/breast_cancer_predictor
